##============================================================================
##  Copyright (c) Kitware, Inc.
##  All rights reserved.
##  See LICENSE.txt for details.
##
##  This software is distributed WITHOUT ANY WARRANTY; without even
##  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
##  PURPOSE.  See the above copyright notice for more information.
##============================================================================

# This file is automatically generated by CMake, do not edit.
VTKm_VERSION = 2.0
VTKm_DIR = D:\BaiduNetdiskDownload\VTK-9.3.0-Accelate-Debug

VTKm_BUILD_SHARED_LIBS = ON
VTKm_ENABLE_CUDA = OFF
VTKm_ENABLE_KOKKOS = OFF
VTKm_ENABLE_OPENMP = OFF
VTKm_ENABLE_TBB = OFF
VTKm_ENABLE_LOGGING = ON
VTKm_ENABLE_RENDERING = OFF
VTKm_ENABLE_GL_CONTEXT = 
VTKm_ENABLE_OSMESA_CONTEXT = 
VTKm_ENABLE_EGL_CONTEXT = 
VTKm_ENABLE_MPI = OFF

VTKm_INCLUDE_FLAGS = -I $(VTKm_DIR)/include
VTKm_LIB_FLAGS = -L $(VTKm_DIR)/lib \
    -lvtkm_source-9.3 \
    -lvtkm_io-9.3 \
    -lvtkm_filter_zfp-9.3 \
    -lvtkm_filter_scalar_topology-9.3 \
    -lvtkm_filter_resampling-9.3 \
    -lvtkm_filter_multi_block-9.3 \
    -lvtkm_filter_image_processing-9.3 \
    -lvtkm_filter_geometry_refinement-9.3 \
    -lvtkm_filter_flow-9.3 \
    -lvtkm_filter_field_transform-9.3 \
    -lvtkm_filter_field_conversion-9.3 \
    -lvtkm_filter_entity_extraction-9.3 \
    -lvtkm_filter_density_estimate-9.3 \
    -lvtkm_filter_contour-9.3 \
    -lvtkm_filter_mesh_info-9.3 \
    -lvtkm_filter_vector_analysis-9.3 \
    -lvtkm_filter_connected_components-9.3 \
    -lvtkm_filter_clean_grid-9.3 \
    -lvtkm_filter_core-9.3 \
    -lvtkm_worklet-9.3 \
    -lvtkm_cont_testing-9.3 \
    -lvtkm_cont-9.3 \
    -lvtkmdiympi_nompi
